### ISSUE TITLE
Make actions testable

### ISSUE THREAD

**Issue by webbertakken** [webbertakken/unity-actions#1]
I see two ways of making actions testable:

- Have a unity project in this repository that can be used to run the pipeline on
- Have a different repository for the same purpose

Things to take into account:

In the [publishing actions](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/publishing-actions-in-github-marketplace#about-publishing-actions) section on github it reads the following:
> Each repository must contain a single action.

This means that maybe we will have to split up each "action" into a separate repository. For example:
  - acquire manual activation file
  - activate using manual activation file
  - test test project

However, if possible (and if it indeed makes sense to do so) I would like to keep these actions together or even combine them to perform multiple scenarios with the same action.

**Comment by James-Pickett** [comment]
Seems like the activation part is going to be needed for any action running in a container. So it seems that keeping that part in one place is a good idea. Do you know if you can persist a container between jobs in a workflow?

**Comment by webbertakken** [comment]
@James-Pickett You could when defining your pipeline in your project repository, but not from the perspective of an action, as each action is self-contained and will be built (and in the future probably cached) separately.

This is indeed what I started out trying when testing the pipeline using these actions. However, I found that we may not need to persist any container if we can use the `-manualLicenseFile` argument in the test command. Perhaps there won't be that many more actions than `test` and `build`, each with their respective options/flags.

**Comment by webbertakken** [comment]
Testing of the first part (request manual activation file) can be tracked in PR https://github.com/webbertakken/unity-actions/pull/2

**Comment by webbertakken** [comment]
> I see two ways of making actions testable:
> - Have a unity project in this repository that can be used to run the pipeline on
> - Have a different repository for the same purpose

Since a sample project seems to be ~80kb, I would say it's feasible to keep it in the actions repository.
