### ISSUE TITLE
Make the readme more beginner friendly

### ISSUE THREAD

**Issue by webbertakken** [webbertakken/unity-actions#14]
I'm planning to make the readme more beginner friendly. 

Work towards that will be tracked here.

Please feel free (anyone) to give any input to what you're currently missing in this repo or one of the actions.

- [x] Revamp builder readme
- [x] Revamp test runner readme
- [x] Revamp actions readme
- [x] Include list of supported Unity versions as per #44

**Comment by webbertakken** [comment]
We could probably also use a nice header image for all readme files to make the repository look a little bit more attractive. Anyone good with graphics?

**Comment by josephbmanley** [comment]
I would definitely appreciate an example. I've completely flopped every time I've tried implementing these actions. lol

**Comment by webbertakken** [comment]
> I would definitely appreciate an example. I've completely flopped every time I've tried implementing these actions. lol

@josephbmanley could you create a new ticket, showing what you've tried? That way it's easier to understand for me and others where you're stuck, so we might improve the readme.

Note that this repository and each separate actions repository individually, all have an example implementation that works.

**Comment by webbertakken** [comment]
Beefed up the documentation for builder significantly in https://github.com/webbertakken/unity-builder/pull/29.

**Comment by webbertakken** [comment]
Beefed up the documentation for this repo in https://github.com/webbertakken/unity-actions/pull/42

**Comment by webbertakken** [comment]
Beefed up the documentation for test runner in https://github.com/webbertakken/unity-test-runner/pull/10
