### ISSUE TITLE
Add support for all versions from 2019.2 on

### ISSUE THREAD

**Issue by webbertakken** [webbertakken/unity-actions#3]
In order to be able to test any project, we need to be able to configure a matrix with unity versions like this:

```yaml
    strategy:
      matrix:
        unity-tag: [2019.2.11f1, 2019.2.11f1-webfl]
```

The challenge however is that the **action** is versioned based on the **repository tag**, whereas the **container** is versioned based on a **docker tag**. Ideally the latter could be controlled with a variable. 

For example, say that action `test` with version `v1` has an image defined starting with `FROM gableroux/unity3d:2019.2.11f1`; how to change the image version tag?

One option could be to make the `FROM` clause dependent on an environment variable say `UNITY_IMAGE_TAG`  (if that's possible at all), 

Possible challenges:
- Variable tag may not be feasible or bad practice
- Having a variable tag in docker might clash with some caching strategies.

Possible solutions:
- Combining action version + unity tag as individual (combined) versions.
- The caching difference may be negligible
- ...

**Comment by webbertakken** [comment]
Having thought about this again. Variable tag might be the most clean solution, because it would prevent the need for 8 separate build actions.

**Comment by webbertakken** [comment]
As pointed out by @pCYSl5EDgo in his single-runner `setup-action` repository [here](https://github.com/pCYSl5EDgo/setup-unity/issues/1#issuecomment-560093760), there are a few disadvantages to using gableroux/unity3d containers directly;

> I respect gableroux's great docker containers.
>
> There are a few disadvantages in gableroux/unity3d.
> 1. Doesn't provide programmers with beta/alpha version Unity.
> 2. Doesn't let programmers 'sudo'.
> 3. Can't build IL2CPP with gableroux/unity3d.

For this it might be necessary to have another repository automatically generate images for each version of Unity. Additionally, specific requirements for each platform can be integrated in separate container images. 

Ultimately that would have the added benefit of also keeping the [Builder](https://github.com/webbertakken/unity-builder/blob/v0.1/test-project/Assets/Editor/Builder.cs) class relatively simple (in later versions this file may be copied directly from the action).

> As long as using gableroux/unity3d docker containers, The GitHub Action owner should be worried about Unity version problem.

For this perhaps @GabLeRoux would be interested in a joined effort for automatically building container images for each version automatically?

It would be good if we could gather some requirements from the community.

**Comment by webbertakken** [comment]
To consolidate the challenge in Github Actions for @Github support the following:

## Variable image challenge

Given [Unity Builder](https://github.com/marketplace/actions/unity-builder) action, there are many triggers to the action evolving, resulting in different "versions".

There are many variables that require the container image to change, preventing us from simply building a separate action or version for each combination;

- Unity editor version: `2018.4.13f1`, `2019.2.11f1`, `2020.1.0a14` and many in between.
- Project target platform: `WebGL`, `Android`, `iOS`, `Switch`, `Linux` and quite a few more.
- The version derived of the Action itself: `v0.1`, `v0.2`, `v1` etc.

From an **Action developer** perspective it would be great if we could version our Action based on the implementation of the action itself (`v0.1`, `v0.2` and so on), like in the official docs, while giving the Action implementer the freedom to change the image based on two variables. Let's call them `unityVersion` and `targetPlatform`.

## Propasal 1

To define input variables or use a strategy matrix to form a tag, that would be used in the Dockerfile like so:

```
FROM repo/unity:{unityVersion}-{targetPlatform}
```

From an **Action developer** perspective It would make sense, because it gives a lot more flexibility and it would entirely solve the challenge.

From an **Action implementer** perspective the same would make a lot of sense. 
One caveat could be that the `dockerRepository` and `dockerImageName` should stay static, for trust reasons: I now only have to check one base image repository, plus the implementation of the Action.

From **Github** perspective I would imagine caching, security and backward compatibility would be very important. For security it would perhaps make sense to only allow `FROM {variable}` statement in the Dockerfile to be changed by input that is defined in `action.yml`. For caching I don't foresee too many problems but I can't speak for your public API.

## Proposal 2

To make the creation of those docker images the responsibility of the Github Action, and allow the Action implementer to use different Dockerfiles based on their input. (this last part is still important, based on the variety)

From an **Action developer** perspective this would also solve the challenge. It would partially prevent sharing containers between separate actions, which might pose a new challenge; the one of each action having to be in it's own repository, as per the specification, so no code sharing between actions.

From an **Action implementer** perspective this would solve the problem as well. However the same caveat applies, as I would now have to check each Dockerfile, plus each base image repository before i start using the action with different variables.

From **Github** perspective this would require caching of actions after the first run. I'm not sure if I can see the full implications of it.

## Proposal 3

Every single variable combination gets released as a version. This would require the interface to become more friendly in two major use cases:

- Firstly the interface of the Marketplace. The button

``` 
[ Use Latest Version ][ v ]
```

might have to be split up into some like

```
[ Action version ][ ImageMajorVersion ][ ImageSuffix ]
```

- Second; currently, new releases notify people that watch the repository. Watching releases only is already the lowest level of subscription to a repository which means that it would make sense to differentiate between major and minor releases.

From an **Action developer** perspective this could work. However it would be a lot more work to release all those versions and there may be less control over the quality of each version.

From an **Action implementer** perspective this would solve the problem mostly. The documentation would still have to explain really well which version of the action to use.

From **Github** perspective this would probably be a ton of work that may not be desirable.

## Summary

We need a reliable way to publish actions that are able to use a variety of possible container image builds, which are still being cached.

Unity containers typically are setup with tags like `repository/unity:{unityVersion}-{buildTarget}` and we're asking Github Actions support team for help.

We would like to hear your thoughs on any of the proposals or learn of your preferred way of how to go about implementing this in Github Actions

**Comment by GabLeRoux** [comment]
This is indeed a good challenge, I'm curious to see how it can be solved. I'll go into more details later, but for now, I'll just share a link to an issue where some people were also interested in github actions support for Unity:  
https://gitlab.com/gableroux/unity3d-gitlab-ci-example/issues/69

**Comment by webbertakken** [comment]
Just for documentation sake, another option would be to indeed create a version per `action version` per `unity version` per `target platform` when referencing the action

Not sure if feasible, but it could look something like this;

```yaml
  - name: Build project
    id: buildStep
    uses: webbertakken/unity-builder@v0.2-${{matrix.unity-version}}-${{matrix.target-platform}}
    env:  
      BUILD_TARGET: ${{matrix.target-platform}}
```

This would cause hundreds of releases and makes it more painful to update the action.

I will test whether or not this is a possibility until we know more about the recommended approach.

**Comment by webbertakken** [comment]
There is an additional blocker for **Proposal 3** above;

Namely that it is currently not possible to use matrix values as part of the version tag for an action in workflows, as showcased [here](https://github.com/webbertakken/unity-builder/pull/8#issuecomment-565717393).

**Comment by umar-ahmed** [comment]
Very interesting discussion here! I am super interested in seeing if we can get this working with a nice experience for all parties.

I'm a total newbie when it comes to Github Actions and even Unity, but I was just doing a quick search into parameterizing the path to the Dockerfile for Docker container actions and I came across this thread on the Github Community support forum: https://github.community/t5/GitHub-Actions/Docker-container-action-with-parametric-Dockerfile-filename/td-p/33175.

Seems like the feature request has been made with the appropriate team, but in the meantime, I was intrigued when the OP replied back with:

> In this case, I've worked around it launching Docker manually with a minimal Javascript action that boots the container with the Dockerfile I want.

I did a little digging and found the action that the OP was working on: https://github.com/marketplace/actions/run-on-architecture. Looking at their repo it looks like they have a bunch of Dockerfiles defined: https://github.com/uraimo/run-on-arch-action/tree/master/Dockerfiles and they use a shell script to spin up the appropriate Docker image. 

It seems like very much a hack to use a Javascript action to connect to Docker like that, but in the short-term, this might be a usable workaround.

**Comment by webbertakken** [comment]
@umar-ahmed 

> I'm a total newbie when it comes to Github Actions and even Unity

I think many of us are. I'm new to both Github Actions and Unity myself as well.

> I did a little digging and found the action that the OP was working on

Great! Thanks a bunch for linking that here. It looks quite promising for the short term.

> It seems like very much a hack to use a Javascript action to connect to Docker like that, but in the short-term, this might be a usable workaround.

I agree this may be a great workaround until we have a native way to do this with Docker.

I will be trying to get that to work if I find enough time. 

For now I have added a few commits to an already existing PR, that is very much a work in progress. Work can be tracked here: https://github.com/webbertakken/unity-builder/pull/8

**Comment by webbertakken** [comment]
Initial support for different images is now implemented.

See: https://github.com/webbertakken/unity-builder/pull/8

**Comment by umar-ahmed** [comment]
@webbertakken That's AWESOME! Will definitely try it out soon.

Also, thanks for the shout-out in the release notes :bowing_man:!

**Comment by webbertakken** [comment]
@umar-ahmed Cool! Although please don't get your hopes up;

I didn't actually test more than the `WebGL` build (which worked before this refactor), and by default the others fail, so it might need more work for some platforms' builds to be fully functional. 

Please feel free to create new tickets for any improvements or bugs or post a PR if you have found any solutions.

**Comment by Filiecs** [comment]
@webbertakken I was able to successful follow your directions and get it to work. I've been slamming my head against this issue for days. You are amazing.
@GabLeRoux You too, thank you so much for your contributions to this.

**Comment by webbertakken** [comment]
This now effectively works.
