### ISSUE TITLE
Unity Actions and Private Repos

### ISSUE THREAD

**Issue by gblikas** [webbertakken/unity-actions#40]
Thanks for supporting the use of Unity through GitHub Actions 😄 

I was wondering if this system is safe to use for private repositories? There is little documentation surrounding it, or perhaps I am missing the link to it.

**Comment by webbertakken** [comment]
Hi @gblikas,

Yes, this is safe to use in your private repos; all code is open source and I'm using semantic versioning.

**Comment by gblikas** [comment]
@webbertakken  

Thanks for the quick response. I was more wondering if any system would accidentally upload code to another open source project where it could be viewable. Essentially, does private stay private?

**Comment by webbertakken** [comment]
Private stays private. At the most I would implement optional tracking to keep track of which errors occur the most. The chance of that being implemented at some point is likely, but there will be an opt-out option in that case.

**Comment by gblikas** [comment]
@webbertakken Where will this information be published?

**Comment by webbertakken** [comment]
I'm not sure whether it will be published at all. Either way it's only going to contain anonymised data, so you don't have to worry about your projects information leaking out.

Also note that in all current versions of all Unity Actions there is no tracking so far. You can just start with the current versions if you have trust issues. 

Versions can not be changed, as they're tracked in version control and released on the marketplace. All code of these actions is open source and free to inspect. (that includes the docker containers from GabLeRoux).
