### ISSUE TITLE
List of supported Unity Versions

### ISSUE THREAD

**Issue by thorgeirk11** [webbertakken/unity-actions#44]
Is there a list for supported Unity versions?

We just switch over to use the latest LTS version (released 2 days ago) and I am not sure if the unity-builder will support switching over.

**Comment by GabLeRoux** [comment]
unity-builder uses gableroux/unity3d which is built here:  
https://gitlab.com/gableroux/unity3d

docker images are published on docker hub here:  
https://hub.docker.com/r/gableroux/unity3d/

The list of available versions can be found in the tags section and if a version is missing, you can find instructions on how to request or propose the missing one(s) in the project’s readme.

I published some versions yesterday so the one you’re looking for is probably already available.

I’ll let @webbertakken answer how to tell the builder which version to use ;)

**Comment by webbertakken** [comment]
My suggestion is to just upgrade all actions to use the version you want (and update any licenses if needed). Post here whatever problems you're running into. If a version works once, it'll keep working if you use specific versions for the actions :)

Technically, if there is a docker image for it, it should also work for all unity-actions (note that test-runner still has an open pr https://github.com/webbertakken/unity-test-runner/pull/10 to also support this).

If you follow the readme of all actions you should succeed. If not, you may regard this as a bug and report it here, so we can possibly fix it. Obviously I only fix bugs that are visible to me through issues in this repository (be sure to include your configuration and results).

**Comment by thorgeirk11** [comment]
The links @GabLeRoux provided are great! 

I think this needs to be included in the documentation

**Comment by webbertakken** [comment]
Great idea! #14

**Comment by webbertakken** [comment]
Added as a checkbox in #14, closing this as your question was answered.
