### ISSUE TITLE
Unity-Builder 2018.4.18f1 - Licence activation not working properly (Specific versions in Docker)

### ISSUE THREAD

**Issue by noiserious** [webbertakken/unity-actions#55]
It seems to be some problem with licence activation for unity version 2018.4.18f1 with the unity builder.

I am running self hosted runners on Ubuntu 18.04 VM running on HyperV
I tested 2019.4.19f1 and it fails the same way.
Version 2018.4.16f1 works just fine however.

```
Successfully built 93ccc5672d15
Successfully tagged unity-builder:2018.4.18f1-windows
/usr/bin/docker run --workdir /github/workspace --rm --env UNITY_LICENSE --env UNITY_LICENSE_FILE --env UNITY_EMAIL --env UNITY_PASSWORD --env UNITY_SERIAL --env UNITY_VERSION=2018.4.18f1 --env PROJECT_PATH=Client --env BUILD_TARGET=StandaloneWindows64 --env BUILD_NAME=Starborne --env BUILD_PATH=build/StandaloneWindows64 --env BUILD_FILE=Starborne.exe --env BUILD_METHOD= --env CUSTOM_PARAMETERS= --env HOME=/github/home --env GITHUB_REF --env GITHUB_SHA --env GITHUB_REPOSITORY --env GITHUB_ACTOR --env GITHUB_WORKFLOW --env GITHUB_HEAD_REF --env GITHUB_BASE_REF --env GITHUB_EVENT_NAME --env GITHUB_WORKSPACE=/github/workspace --env GITHUB_ACTION --env GITHUB_EVENT_PATH --env RUNNER_OS --env RUNNER_TOOL_CACHE --env RUNNER_TEMP --env RUNNER_WORKSPACE --volume *** --volume *** --volume *** --volume *** unity-builder:2018.4.18f1-windows
Requesting activation (professional license)
Initiating legacy licensing module

LICENSE SYSTEM [2020317 11:12:42] Next license update check is after 2020-02-14T17:14:57


LICENSE SYSTEM [2020317 11:12:42] 1162a55aa3gb4234517b45g2073f73 != c04bdg1e9aa32349c51e08cb91009d0


LICENSE SYSTEM [2020317 11:12:42] 1162a55aa3023456fbc417b45f2073f73 != c04b961e91f3a9c51e08cb91009d0

DisplayProgressbar: Unity license
[0317/111242:ERROR:browser_main_loop.cc(161)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[0317/111243:ERROR:sandbox_linux.cc(308)] InitializeSandbox() called with multiple threads in process gpu-process
[UnityConnectServicesConfig] config is NOT valid, switching to default
Cancelling DisplayDialog: Failed to activate/update license. Timeout occured while trying to update license. Please try again later or contact support@unity3d.com
This should not be called in batch mode.
 
(Filename: /home/builduser/buildslave/unity/build/Editor/Platform/Linux/EditorUtility.cpp Line: 257)

Unclassified error occured while trying to activate license.
Exit code was: 1
##[error]The process '/usr/bin/docker' failed with exit code 1
```

**Comment by webbertakken** [comment]
Hi @noiserious, 

Thanks for sending this report. Lets have a look at how to solve it.

It looks like you're using a professional license. Did you make sure this license is valid for both versions that you're trying to activate one?

Could you also share your workflow? Without it, it's quite hard for me to figure out what's going wrong.

**Comment by noiserious** [comment]
Hi @webbertakken 
I was not aware that the licence would be limited to small version changes like that, but I'll have a look :)

Here is the workflow portion for the Client, I'll try to accept view request as soon as I can.
https://drive.google.com/file/d/10bh6QJ6efbyeCYkBpCiz4_ZA2H2esN6m/view?usp=sharing

**Comment by noiserious** [comment]
I just noticed, @webbertakken 
The workflow I sent you actually has in line 69. 2018.4.16f1,
The one that does not work only has that changed to 2018.4.18f1,

**Comment by webbertakken** [comment]
Personally I can only test with a personal license, and I've found that sometimes different versions require different activation files.

I've looked at your config. It looks perfectly fine so that shouldn't be the issue.

Let me know if you can find anything related to activating pro licenses for different versions of unity. I recall other people having had similar trouble with licenses, but only when different versions were used.

**Comment by noiserious** [comment]
Spent some time to get this working for 2019.3 today, it has the same issues.
It seems to be just a issue with unity licence activation in Docker containers in general. I tried most of the workarounds I could find with a fork of unity-builder, but with no success.

[](https://issuetracker.unity3d.com/issues/cannot-activate-license-within-a-docker-container) 

On in my team fell back to using unity personal one time activation method, and it seems to be available for the professional licence as well?.. Don't quote me on that though :)
Licence is registered to a machine key, I guess we can do that since we have our runners running on a dedicated machine.

**Comment by webbertakken** [comment]
Please note that this doesn't affect all versions of 2019.3.
For example it works using `2019.3.8f1` without any problem for me.

@noiserious Could you perhaps specify the specific version in your post above that didn't work for future reference?

**Comment by noiserious** [comment]
Version `2019.3.14f1` does not seem to work. 
Updated above comment as well

**Comment by webbertakken** [comment]
Related https://github.com/webbertakken/unity-actions/issues/70
