### ISSUE TITLE
Cancel workflow does not cancel Unity Build.

### ISSUE THREAD

**Issue by noiserious** [webbertakken/unity-actions#56]
#### What is wrong
It seems that cancelling a workflow while Unity-Builder is running, does not actually cancel the unity build process.

#### Reproduce
When a Unity-Build starts, Cancel the workflow and see running processes on your build machine.
The runner should successfully terminate but the Unity process should still be active and taking up resources.

#### Expected
When a runner is cancelled, it should stop all processes it was managing.

#### Context
This is running on a Ubuntu 18.04 virtual machine as a Self-Hosted runner.
Unity Version 2018.4.16f1

**Comment by thorgeirk11** [comment]
I am also encountering this issue

**Comment by webbertakken** [comment]
I was just able to cancel 6 concurrent builds without a problem. It's possible that GitHub has fixed this issue by themselves. @noiserious @thorgeirk11 Could you please confirm whether this is still a problem for you or not?

**Comment by noiserious** [comment]
I will check it out early next week and let you know.

**Comment by noiserious** [comment]
Finally got around checking this out.
Its still seems to be a problem on our build server. Are you running them as self hosted?

Its running as a self hosted runner on dedicated Ubuntu 18.04 machine. Their setup as a service with the tool GitHub-Actions ships with their runners.

**Comment by webbertakken** [comment]
I'm not running them as self-hosted. Just on the default runners.

**Comment by webbertakken** [comment]
This doesn't seem to have been an issue for some time anymore. Assuming solved or no longer relevant.

**Comment by spaskhalov** [comment]
I'm not sure, that my issue related to that problem (https://github.com/actions/virtual-environments/issues/709). The problem I'm talking about is reproduced as follows:
**Environment**
github actions runner installed on self-hosted VM with Ubuntu 20.04
**Steps**
- Run workflow.
- Cancel workflow, during running tests or building Unity app.
- Action will be successfully canceled, but the Unity process exists on the VM for a few more minutes (apparently until the end of the tests or the build process). I use top command to check process on VM.
_This is random output from top command, during Unity still exists:_
```
 381700 root      20   0 9080156 900392 188120 S 201.7  11.3   2:25.85 Unity                                                                                   
 381730 root      20   0  989052  97760  27172 S  37.0   1.2   0:17.03 UnityPackageMan                                                                         
    526 root      20   0 1194536  22144    708 S   0.3   0.3  19:58.39 containerd           
```
```
381700 root      20   0 9744352   1.2g 240808 S 286.4  15.5   6:11.16 Unity                                                                                   
   526 root      20   0 1194536  22144    708 S   0.3   0.3  19:58.59 containerd         
```

Then there are two options:
1) In most cases at some time process completes successfully and does not consume the resources of the virtual machine.
2) Sometimes the process turns into a "zombie" and never ends. Machine resources are busy all the time, and the speed of execution of subsequent actions is significantly reduced.

In a few hours of testing, I was unable to complete case 2 to collect the logs. But sometimes I notice that our machine starts to work slowly and I have to connect and kill the unit process with my hands. I'm pretty sure that the problem that Unity process not being canceled along with the cancellation of github action is related to this zombie process.

This is logs, with "canceled" action and full workflow file.
[unityBuild.yml.zip](https://github.com/game-ci/unity-actions/files/6248384/unityBuild.yml.zip)
[canceled_run_logs_478.zip](https://github.com/game-ci/unity-actions/files/6248378/canceled_run_logs_478.zip)

**Comment by webbertakken** [comment]
Perhaps the cause is not the same, but to me it looks to be relevant information.

Either way I believe this is not something we can solve from Unity actions side, but something that should be discussed within Github Actions - specifically regarding running docker (in this case the Unity editor container ran from JavaScript).

If you believe otherwise, that would definitely be great; in that case we need to figure out the cause or what we could change. Until then I believe it's best to leave this closed to prevent having unactionable items.

**Comment by spaskhalov** [comment]
I'm agree with you, that it's looks like wider problem. Not relative to Game CI and is connected with running docker actions on self hosted runners. 
I will try to post issue in runner repo.
