### ISSUE TITLE
IL2CPP support for Standalone

### ISSUE THREAD

**Issue by 06Games** [webbertakken/unity-actions#57]
**Describe the solution you'd like**
I would like to be able to build my project with IL2CPP
And you could also add an option to delete the *_BackUpThisFolder_ButDontShipItWithYourGame* folder.

**Describe alternatives you've considered**
I went back to a Mono build

**Additional context**
[With](https://github.com/06-Games/Suivi-Scolaire/actions/runs/63183988/workflow) / [Without](https://github.com/06-Games/Suivi-Scolaire/actions/runs/63195571/workflow) IL2CPP

**Comment by GabLeRoux** [comment]
This will need to be supported in the docker images. Here's a related issue:  
https://gitlab.com/gableroux/unity3d/-/issues/66

**Comment by webbertakken** [comment]
@knxrb With they, you mean the person you're talking to above? 😄

Anyway, the linked issue seems to be clear and the last comment indicates it's working.

I guess the next step is for Unity Builder to allow for a parameter that allows selecting il2cpp images. Probably [the image functionality](https://github.com/webbertakken/unity-builder/blob/master/src/model/image-tag.js#L34) has to be extended for this. Anyone is free to send a PR with the required changes.

**Comment by knxrb** [comment]
Oh yeah >.< I didn't notice that it's the same guy for the images. I've only just started looking at and using these actions this afternoon.

I'll have a look at what's needed for this tomorrow and see if I can get it working.

Thanks for the info :+1:

**Comment by knxrb** [comment]
@webbertakken I've had a quick look at this and from what I understand: this can't be done yet as there's only linux IL2CPP images?

The image suffix is being set to `windows` when building `StandaloneLinux64`:
https://github.com/webbertakken/unity-builder/blob/master/src/model/image-tag.js#L54

**Comment by webbertakken** [comment]
Linux support for IL2CPP should work out of the box, same for Android and iOS builds, whereas macOs and Windows will require these platforms to be used in the base image. This is currently not planned but a welcome addition to the repo that holds the docker images [here](https://github.com/Unity-CI/docker).
