### ISSUE TITLE
Android Build Fails

### ISSUE THREAD

**Issue by davidmfinol** [webbertakken/unity-actions#60]
Android build runs for over an hour and fails with an out of space error.

**To Reproduce**
- Run this workflow: https://github.com/finol-digital/Card-Game-Simulator/actions/runs/67665287

**Expected behavior**
Android build should succeed. 

**Additional Context**
From [the other thread](https://github.com/webbertakken/unity-actions/issues/12#issuecomment-606807920). 
> 
> To me it looks like one of the steps takes 51 minutes as indicated by [Android PostProcess task "IL2CPP" took 3064730.3235 ms](https://github.com/finol-digital/Card-Game-Simulator/runs/549232647?check_suite_focus=true#step:5:6108), and after an hour github actions pulls the filesystem from under the running action, would by my guess. Even though the [docs](https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits) say that execution can last up to 6 hours.
>

**Comment by davidmfinol** [comment]
The last time I tried testing the build on my laptop, I was still on Unity 2018.4.19f1 and it took 5 min. 

Now I'm running with 2018.4.20f1 on my laptop and it is taking much longer. 
It's looking like this issue may be with Unity 2018.4.20f1.

**Comment by sdegetaus** [comment]
I am having the same issue. I believe it could be related to this issue:
https://issuetracker.unity3d.com/issues/il2cpp-build-hangs-while-building-a-project-with-a-large-array-of-strings

**Comment by davidmfinol** [comment]
I found [someone else ran into the same error in GitHub Actions for a non-Unity project](https://github.community/t5/GitHub-Actions/BUG-Strange-quot-No-space-left-on-device-quot-IOExceptions-on/m-p/47691#M6920).

Their workaround [broke my WebGL builds](https://github.com/finol-digital/Card-Game-Simulator/actions/runs/70905797), but it [fixed my Android builds](https://github.com/finol-digital/Card-Game-Simulator/actions/runs/70958545)! 

The WebGL builds were just an experiment, and Web isn't a platform I'm focusing on (yet), so I'm happy.

**Comment by sdegetaus** [comment]
> I found [someone else ran into the same error in GitHub Actions for a non-Unity project](https://github.community/t5/GitHub-Actions/BUG-Strange-quot-No-space-left-on-device-quot-IOExceptions-on/m-p/47691#M6920).
> 
> Their workaround [broke my WebGL builds](https://github.com/finol-digital/Card-Game-Simulator/actions/runs/70905797), but it [fixed my Android builds](https://github.com/finol-digital/Card-Game-Simulator/actions/runs/70958545)!
> 
> The WebGL builds were just an experiment, and Web isn't a platform I'm focusing on (yet), so I'm happy.

This worked for me as well! Great finding and thanks for sharing 💪

**Comment by davidmfinol** [comment]
@sdegetaus How are you signing your Android builds? Are you also using a [custom build method](https://github.com/finol-digital/Card-Game-Simulator/blob/develop/Assets/Editor/BuildCGS.cs#L11) and [passing in secrets](https://github.com/finol-digital/Card-Game-Simulator/blob/develop/.github/workflows/main.yml#L53)?

I only ask because I'm wondering how we can help with making Android builds easier for others that might use Unity Actions.

**Comment by davidmfinol** [comment]
I updated to 2018.4.21f1 and my Android builds broke.

@GabLeRoux Does the Docker image for 2018.4.21f1 not have the Android NDK?

**Comment by GabLeRoux** [comment]
```bash
skopeo --override-os linux inspect docker://gableroux/unity3d:2018.4.21f1-android | jq '.Labels'
```
```json
{
  "build-date": "2020-04-14T16:10:52+0000",
  "com.gableroux.unity3d.build": "f1",
  "com.gableroux.unity3d.download_url": "https://beta.unity3d.com/download/fd3915227633/UnitySetup-2018.4.21f1",
  "com.gableroux.unity3d.release_notes": "https://unity3d.com/unity/whats-new/2018.4.21f1",
  "com.gableroux.unity3d.release_url": "https://beta.unity3d.com/download/fd3915227633/public_download.html",
  "com.gableroux.unity3d.sha1": "7ba4699e974e23cdd09ba0b334125d14ae459a27",
  "com.gableroux.unity3d.tag": "2018.4.21f1-android",
  "com.gableroux.unity3d.version": "2018.4.21",
  "com.gitlab.ci.build": "https://gitlab.com/gableroux/unity3d/builds/510562614",
  "com.gitlab.ci.builder": "lebreton.gabriel@gmail.com",
  "com.gitlab.ci.pipeline": "https://gitlab.com/gableroux/unity3d/pipelines/135883637",
  "com.gitlab.ci.ref": "master",
  "vcs-url": "https://gitlab.com/gableroux/unity3d"
}
```

Android docker image build log available here:  
https://gitlab.com/gableroux/unity3d/builds/510562614

From build log, following NDK is being used:  
ANDROID_NDK=http://dl.google.com/android/repository/android-ndk-r19-linux-x86_64.zip

Here are some additional output for the following commands inside the docker image:  
https://app.circleci.com/pipelines/github/GabLeRoux/circleci-unity3d-playground/5/workflows/cc1939cb-f9c3-41b6-8122-ab8ccca87fff/jobs/8

```bash
java -version
/opt/Unity/Editor/Data/PlaybackEngines/AndroidPlayer/SDK/tools/bin/sdkmanager --list
/opt/Unity/Editor/Data/PlaybackEngines/AndroidPlayer/SDK/tools/bin/sdkmanager --version
```

```
[...]
  ndk-bundle                                                                               | 21.0.6113669 | NDK 
```

I'm quite sure it's there, so you'll need to provide more details ;)

**Comment by davidmfinol** [comment]
This is what I'm seeing in [my build logs](https://github.com/finol-digital/Card-Game-Simulator/runs/593910082?check_suite_focus=true#step:6:5327):
```
 File /root/.android/repositories.cfg could not be loaded.

...

Android PostProcess task "Detecting Android SDK" took 19523.3979 ms
DisplayProgressbar: Detect Android NDK
UnityException: Android SDK not found
Unable to locate Android NDK.
```

Is the problem this /root/.android/repositories.cfg file?

Also, I see in the other thread you mentioned:
> Someone else confirmed versions before 2019.3.0 requires r16

But it looks like you're using r19 for 2018.4.21f1. Could that be part of the problem?

**Comment by GabLeRoux** [comment]
Ah you're right, I fixed previous 2018 versions, but this one was published recently and forgot that technical detail.

I'll fix the generator to avoid making these mistakes again. Thanks for letting me know, I'll make sure this is fixed for future 2018 images 👍

**Comment by GabLeRoux** [comment]
There you go, found a few minutes during lunch break:  
https://gitlab.com/gableroux/unity3d/-/merge_requests/107

You can try again once the pipeline from master green. Should be ok in ~1h 👍

**Comment by davidmfinol** [comment]
It works, thanks!!!

**Comment by webbertakken** [comment]
> > I found [someone else ran into the same error in GitHub Actions for a non-Unity project](https://github.community/t5/GitHub-Actions/BUG-Strange-quot-No-space-left-on-device-quot-IOExceptions-on/m-p/47691#M6920).
> > Their workaround [broke my WebGL builds](https://github.com/finol-digital/Card-Game-Simulator/actions/runs/70905797), but it [fixed my Android builds](https://github.com/finol-digital/Card-Game-Simulator/actions/runs/70958545)!
> > The WebGL builds were just an experiment, and Web isn't a platform I'm focusing on (yet), so I'm happy.
> 
> This worked for me as well! Great finding and thanks for sharing 💪

@davidmfinol @sdegetaus related: Possible better and scalable solution: https://github.com/webbertakken/unity-actions/issues/64

**Comment by SethCram** [comment]
> Android build runs for over an hour and fails with an out of space error.
> 
> **To Reproduce**
> 
>     * Run this workflow: https://github.com/finol-digital/Card-Game-Simulator/actions/runs/67665287
> 
> 
> **Expected behavior** Android build should succeed.
> 
> **Additional Context** From [the other thread](https://github.com/webbertakken/unity-actions/issues/12#issuecomment-606807920).
> 
> > To me it looks like one of the steps takes 51 minutes as indicated by [Android PostProcess task "IL2CPP" took 3064730.3235 ms](https://github.com/finol-digital/Card-Game-Simulator/runs/549232647?check_suite_focus=true#step:5:6108), and after an hour github actions pulls the filesystem from under the running action, would by my guess. Even though the [docs](https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits) say that execution can last up to 6 hours.

Unfortunately, the link posted previously in the thread for a fix is dead. Could anyone in this thread detail what the bypass was? It's my first time building for Android and my project isn't particularly large but I'm encountering this same problem.

**Comment by davidmfinol** [comment]
Running out of disk space is a common issue: https://game.ci/docs/troubleshooting/common-issues#no-space-left-on-device

**Comment by SethCram** [comment]
> Running out of disk space is a common issue: https://game.ci/docs/troubleshooting/common-issues#no-space-left-on-device
> 
> My recommendation is to use the free disk space action. Any example workflow that builds for Android should have it

Thanks for pointing me in the right direction! I was able to get my workflow working with the help of the free disk space action.
