### ISSUE TITLE
Large project workflow/Scaling up the use of these actions

### ISSUE THREAD

**Issue by frostebite** [webbertakken/unity-actions#64]
**Is your feature request related to a problem? Please describe.**
These actions are super useful and fast for building Unity projects, but most of my projects quickly exceed github's build runner disc size of 14 GB (this is for everything including the OS), especially when you consider the size of the Library folder/imported assets. Unity projects get large (in terms of disc space) pretty quick so I think this is an issue many people would run into.

The main option github offers to get around this is self hosted runners. This can be both pricy, time consuming to setup and wasteful because the runner may not be used for long periods.

I've looked into a lot of automation with self hosted runners and it's not a great or stable option at the moment. Via VMs the price quickly escalates and the automation is slow, and doing it via kubernetes is not possible for these actions because they require docker to be accessible on the machine running the build. 

**Describe the solution you'd like**
For dynamic and changing compute workloads like this Kubernetes is an excellent platform. 'Project Argo' is a system that runs on Kuberenetes for workloads like build systems/jobs/ML training (basically one off runs and pipelines).

It would be excellent if each of these actions could be run on Argo. Kubernetes allows workers to be scaled, volumes/discs to be provisioned and cleaned up of any size and that suits Unity CI needs really well. And Argo fundamentally is just a platform that allows for running docker images so the amount of work may not be too vast...

Argo is easy to setup on a cluster and with many cloud providers this can be done via the GUI.

This would give the most streamlined out of the box way to support builds of projects of any size.

**Describe alternatives you've considered**
An alternative would be to offer a way to run the actions you've provided without using Github actions as docker containers and leave the rest up to the user. Either by providing them as node js versions or simply making it possible to clone a particular repo and run scripts to accomplish the same result as these actions.

**Additional context**
This is something I'd be really happy to help build! Thanks for these great actions otherwise.

**Comment by webbertakken** [comment]
@frostebite I love this idea and I think it would be a great way to reliably scale for bigger architectures.

More people have ran into this problem. I've linked the relative thread above.

Personally I've also ran into the issue of actions usage (bandwidth and storage in my case) being quite high. So I still end up paying for my little hobby project, because i build often.

As for implementation details, we could simply give users the option to run in the default mode (current) or a "cloud" mode here: https://github.com/webbertakken/unity-builder/blob/40564afbaf40fc026a1eb69afd1c3c3a9077aa2e/src/index.js#L17

The second mode would obviously require a few more things to configure, but it would give the added benefit of keeping the code in one place (per action).

**Comment by webbertakken** [comment]
Also feel free to join us on [discord](totema.studio/discord) where we discuss unity CI related things regularly. 

We might need to narrow down some implementation details on this one

**Comment by frostebite** [comment]
Sounds good. 

It would make sense to review some github actions that make it easy to run Argo workflows, to see how they approach logs and artifacts, and what kind of experience they manage to achieve.

Here is the main one that seemed noteworthy:
- https://github.com/machine-learning-apps/actions-argo

I'll jump on discord, but perhaps it would make sense to continue to track further notes on this topic here.

**Comment by frostebite** [comment]
We spoke on discord about how to approach building this.

We discussed the following:
- We want to make the approach as beginner friendly as possible. Ideally the approach would also be cloud provider agnostic.
- Using GCP Cloud Run or AWS Fargate would make things easier than using Kubernetes and Argo because you wouldn’t need a cluster setup and running. However they also have limited disc space and this doesn’t suit Unity projects. So, Kubernetes will still be the easiest option for scaling out.
- Argo is worth the setup because raw Kubernetes resources do not offer things like garbage collection of completed jobs, parallelism limits, improved experience for ephemeral storage and artifact handling.
- We also considered using Airflow instead of Argo. But Argo can use Kubernetes authentication configuration, Airflow would require additional configuration for authentication. This means using Argo would have less configuration overhead and be easier to setup for Kubernetes.
- We also noted setup for some platforms that require an SDK might be very tedious using this approach. And using Windows containers is both expensive at experimental at this point in time. For these platforms using a GitHub self hosted runner may be a more straightforward option.

A couple of considerations came up while investigating further that I wanted to raise:
 - We should also discuss that we would have to push a docker image to a registry for every run with this approach. Perhaps the cost and bandwidth consumption would be an issue?
- These actions do provide a clean user friendly way to use Gab’s docker images. But, perhaps a user might ask why Argo (a project which offers CI capabilities) can’t be used to accomplish this without any use of Github actions. (Or by downloading the artifact produced by Argo with no dependency between the systems) I’m not sure how challenging it would be to reuse the code of these actions on another CI system, separated from actions. Perhaps this can be a secondary goal? 
- Should the Argo based cloud actions be separate actions or parameters in the existing actions?

**Comment by webbertakken** [comment]
We had another followup on discord, as linked above.

Here's another quick summary to keep things transparent;

- So far we're thinking of using a parameterised approach where the default would use a GitHub runner, and additional configuration would add the option of running the job in the cloud. Specifically using Argo in our first approach.
- The first step will be about figuring out the implementation details about getting the image, with or without the project already in it, and with or without the actions build script included.
- We considered the code repositories of Unity projects, already being at GitHub being easy to transfer to Actions and there being two ways to get them to another system, running the job, between which there is no clear preference until we see more implementation details;
    - Including it in the image and pushing it
    - Including only the instructions to pull the repository
- Lastly we agreed that the unity actions are more than just a bootstrapper for Gab's images, which means that there is value to keeping the implementation for both approaches in one place (think of things like versioning, the out-of-the-box build script and other pre-build functionality and configuration.

@frostebite was so nice to offer to take the lead on the development of this feature. Unity Actions will be giving full support to their efforts. 

As the size of this feature may turn out to become sizeable over time, we respect working in iterations and possibly merging unfinished or undocumented features while it is still under active development.

**Comment by webbertakken** [comment]
Implementation is near complete. We are looking into funding for a cluster so the example workflow will be tested as part of every pull request.

**Comment by frostebite** [comment]
Now that https://github.com/webbertakken/unity-builder/pull/124 has been merged, it is possible to supply a Kubernetes configuration to the unity-builder action. This will then run the build in a container in the Kubernetes cluster. By using the input parameters kubeContainerMemory, kubeContainerCPU and kubeVolumeSize, you can run very large builds in a Kubernetes cluster.
