### ISSUE TITLE
Unity 2019.4.1f1 Fails with Unity-Builder

### ISSUE THREAD

**Issue by dydgus5120** [webbertakken/unity-actions#72]
I'm trying to build a project with Unity-Builder

Unity Version: 2019.4.1f1
And I get the following error.

```
manifest for gableroux/unity3d:2019.4.1f1-windows not found: manifest unknown: manifest unknown
##[error]The process '/usr/bin/docker' failed with exit code 1
```

https://github.com/webbertakken/unity-actions/issues/52
I saw this article.

I looked into docker and there was 2019.4.0f1.
So I changed the workflow setting to unityVersion: 2019.4.0f1 and ran it.

Still, it failed.
```
total 8.0K
drwxr-xr-x 2 root root 4.0K Jun 22 23:18 
drwxr-xr-x 3 root root 4.0K Jun 22 23:18 ..
##[error]The process '/usr/bin/docker' failed with exit code 1
```

What is the problem?

The project version is 2019.4.1f1.

Do you have to match the version set in the workflow with the project version?

**Comment by Noxalus** [comment]
Containers with this Unity version are not ready yet: https://hub.docker.com/r/gableroux/unity3d/tags.

**Comment by webbertakken** [comment]
Correct. As the readme of this repo reads: 

> Unity Actions are based on the [unity3d](https://gitlab.com/gableroux/unity3d) images from [GabLeRoux](https://github.com/GabLeRoux). 
> Any version in this [list](https://hub.docker.com/r/gableroux/unity3d/tags) can be used to test and build projects.

That means you'll have to open a ticket in the repo for the docker images.
