### ISSUE TITLE
Unity Unit Test In Play Model 

### ISSUE THREAD

**Issue by ZhouJiaZhi** [webbertakken/unity-actions#78]
The sample playmode test case is so simple， can you provide a more complicated example ， using gameobject and entity in your unit test case

**Comment by webbertakken** [comment]
@ZhouJiaZhi thank you for your request.

I fully agree it's not such a complicated example, but I also found it's quite a bit of a learning curve and a bit of work to get started with unity tests. Any improvements would be very much appreciated and anyone is free to contribute any improvements.

**Comment by webbertakken** [comment]
Closing this for low demand. PRs are always welcome of course. Proper play tests seem to be uncommon. Awaiting perhaps some contributions for bigger game developers.

Closing for now.
