### ISSUE TITLE
unity 2019LTS Build Failed

### ISSUE THREAD

**Issue by ZhouJiaZhi** [webbertakken/unity-actions#80]
I use unity 2019.4.4f1 for run unity action and get failed ，but I use 2019.2.11f would get pass
<img width="788" alt="Screen Shot 2020-07-27 at 10 30 01 PM" src="https://user-images.githubusercontent.com/20750357/88554183-c7711d80-d058-11ea-853e-4474bbea7f0e.png">

**Comment by ZhouJiaZhi** [comment]
my repo 
git@github.com:ZhouJiaZhi/test-secret.git

**Comment by ZhouJiaZhi** [comment]
And I have another two question
1.could this support git submodule ？
2.my repo using nuget for import third party package,could this support ?
reference :
git@github.com:GlitchEnzo/NuGetForUnity.git

**Comment by webbertakken** [comment]
Did you update the license for 2019.4?

Could you also please provide http links instead of an ssh reference?

**Comment by ZhouJiaZhi** [comment]
@webbertakken 
Below is the https link, Thank you for you 
https://github.com/ZhouJiaZhi/test-secret.git

**Comment by webbertakken** [comment]
You will have to update the license.

From your logs:

```
LICENSE SYSTEM [2020727 10:28:18] bbc1cb99063843499779e57fc056d8ad != 9EA140DC-07DC-50A4-8CED-7830F267F477


LICENSE SYSTEM [2020727 10:28:18] bbc1cb99063843499779e57fc056d8ad != C02Z51CCLVDQ```

**Comment by ZhouJiaZhi** [comment]
well,I renewed my license again today but failed, may I use this license in your repo? And do you know when your license will expire
<img width="1289" alt="Screen Shot 2020-07-29 at 10 38 14 PM" src="https://user-images.githubusercontent.com/20750357/88814038-32069280-d1ec-11ea-83d0-21447c49ae9d.png">

**Comment by webbertakken** [comment]
No, kindly use your own license.

You should renew your license using the **exact same steps** you followed before, using the alf file that's generated by the unity version that you would like. See https://unity-ci.com/docs/github/activation

**Comment by ZhouJiaZhi** [comment]
OK, I will try it later, Thank you
